/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/

package org.jax.cs.jcmsWebInstaller;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author cnh
 */
public class InstallationFailedPanel extends JCMSPanel {

    /**
     * Creates new form InstallationCompletePanel
     */
    public InstallationFailedPanel(JDesktopPane desktopPane, JFrame frame) {
        super.JCMSPanel(desktopPane, frame);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lblJCMSWebFoum = new javax.swing.JLabel();
        lblFAQs = new javax.swing.JLabel();
        lblKnownIssues = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JCMS Web Installation Failed");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtMessage.setEditable(false);
        txtMessage.setColumns(20);
        txtMessage.setLineWrap(true);
        txtMessage.setRows(5);
        txtMessage.setText("JCMS Web installation failed.  Please review the installation notes on the previous page for hints on how to resolve minor issues.  On the other hand, if you have exhausted your options please submit a support request using \"JCMS Web Forum\".  \n\nJCMS support links listed below.\n\nNext page lists all JCMS resource links.\n\n");
        txtMessage.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtMessage);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonNextActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonNextActionPerformed(evt);
            }
        });

        lblJCMSWebFoum.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSWebFoum.setText("JCMS Web Forum (click here to submit a support request)");
        lblJCMSWebFoum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSWebFoum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSWebFoumMouseClicked(evt);
            }
        });

        lblFAQs.setForeground(new java.awt.Color(0, 0, 255));
        lblFAQs.setText("Frequently Asked Questions - FAQs");
        lblFAQs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFAQs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFAQsMouseClicked(evt);
            }
        });

        lblKnownIssues.setForeground(new java.awt.Color(0, 0, 255));
        lblKnownIssues.setText("Known Issues");
        lblKnownIssues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKnownIssues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKnownIssuesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJCMSWebFoum)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKnownIssues)
                            .addComponent(lblFAQs))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJCMSWebFoum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFAQs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKnownIssues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(backButton))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonNextActionPerformed
        this.previousPanel(this, this.getJcmsView());
    }//GEN-LAST:event_backButtonNextActionPerformed

    private void nextButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonNextActionPerformed
        this.nextPanel(this, this.getJcmsView().getResourcePanel(), this.getJcmsView());
    }//GEN-LAST:event_nextButtonNextActionPerformed

    private void lblJCMSWebFoumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSWebFoumMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebForumURL());
    }//GEN-LAST:event_lblJCMSWebFoumMouseClicked

    private void lblFAQsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFAQsMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebFAQsURL());
    }//GEN-LAST:event_lblFAQsMouseClicked

    private void lblKnownIssuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKnownIssuesMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebKnownIssuesURL());
    }//GEN-LAST:event_lblKnownIssuesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFAQs;
    private javax.swing.JLabel lblJCMSWebFoum;
    private javax.swing.JLabel lblKnownIssues;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
