/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/

package org.jax.cs.jcmsWebInstaller;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author cnh
 */
public class JCMSResourcePanel extends JCMSPanel {
    private Connector connector = null;

    /**
     * Creates new form JCMSResourcePanel
     */
    public JCMSResourcePanel(JDesktopPane desktopPane, JFrame frame) {
        super.JCMSPanel(desktopPane, frame);
        initComponents();
    }
    
    public void initialize() {
        this.connector = ((JCMSWebInstallerApp)this.getFrame()).getConnector();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblJCMSWebFoum = new javax.swing.JLabel();
        lblFAQs = new javax.swing.JLabel();
        lblKnownIssues = new javax.swing.JLabel();
        lblJCMSHome = new javax.swing.JLabel();
        lblJCMSTutorials = new javax.swing.JLabel();
        lblJCMSProducts = new javax.swing.JLabel();
        lblJCMSSupport = new javax.swing.JLabel();
        lblJCMSWebInstallationGuide = new javax.swing.JLabel();
        lblJCMSUsersGuide = new javax.swing.JLabel();

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonNextActionPerformed(evt);
            }
        });

        closeButton.setText("Finish");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonNextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JCMS Resources");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblJCMSWebFoum.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSWebFoum.setText("JCMS Web Forum");
        lblJCMSWebFoum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSWebFoum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSWebFoumMouseClicked(evt);
            }
        });

        lblFAQs.setForeground(new java.awt.Color(0, 0, 255));
        lblFAQs.setText("Frequently Asked Questions - FAQs");
        lblFAQs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFAQs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFAQsMouseClicked(evt);
            }
        });

        lblKnownIssues.setForeground(new java.awt.Color(0, 0, 255));
        lblKnownIssues.setText("Known Issues");
        lblKnownIssues.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKnownIssues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKnownIssuesMouseClicked(evt);
            }
        });

        lblJCMSHome.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSHome.setText("JAX Colony Management System - JCMS");
        lblJCMSHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSHomeMouseClicked(evt);
            }
        });

        lblJCMSTutorials.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSTutorials.setText("JCMS Tutorials");
        lblJCMSTutorials.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSTutorials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSTutorialsMouseClicked(evt);
            }
        });

        lblJCMSProducts.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSProducts.setText("JCMS Products");
        lblJCMSProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSProductsMouseClicked(evt);
            }
        });

        lblJCMSSupport.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSSupport.setText("JCMS Support");
        lblJCMSSupport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSSupport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSSupportMouseClicked(evt);
            }
        });

        lblJCMSWebInstallationGuide.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSWebInstallationGuide.setText("JCMS Web Installation Guide");
        lblJCMSWebInstallationGuide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSWebInstallationGuide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSWebInstallationGuideMouseClicked(evt);
            }
        });

        lblJCMSUsersGuide.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSUsersGuide.setText("JCMS Web User's Guide");
        lblJCMSUsersGuide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSUsersGuide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSUsersGuideMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJCMSUsersGuide)
                    .addComponent(lblJCMSWebFoum)
                    .addComponent(lblKnownIssues)
                    .addComponent(lblFAQs)
                    .addComponent(lblJCMSSupport)
                    .addComponent(lblJCMSProducts)
                    .addComponent(lblJCMSTutorials)
                    .addComponent(lblJCMSWebInstallationGuide)
                    .addComponent(lblJCMSHome))
                .addContainerGap(366, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblJCMSHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSWebInstallationGuide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSUsersGuide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSSupport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSTutorials)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSWebFoum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFAQs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKnownIssues)
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(backButton))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonNextActionPerformed
        this.previousPanel(this, this.getJcmsView());
    }//GEN-LAST:event_backButtonNextActionPerformed

    private void closeButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonNextActionPerformed
        this.getPropertiesDTO().copyJCMSQuickStartInstructionsToDesktop(this.connector.getInputDTO().getWebInstallationDirectory());
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSQuickStartInstructions(this.connector.getInputDTO().getWebInstallationDirectory()));
        System.exit(0);
    }//GEN-LAST:event_closeButtonNextActionPerformed

    private void lblJCMSWebFoumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSWebFoumMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebForumURL());
    }//GEN-LAST:event_lblJCMSWebFoumMouseClicked

    private void lblFAQsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFAQsMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebFAQsURL());
    }//GEN-LAST:event_lblFAQsMouseClicked

    private void lblKnownIssuesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKnownIssuesMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebKnownIssuesURL());
    }//GEN-LAST:event_lblKnownIssuesMouseClicked

    private void lblJCMSHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSHomeMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSHomeURL());
    }//GEN-LAST:event_lblJCMSHomeMouseClicked

    private void lblJCMSTutorialsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSTutorialsMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSTutorialsURL());
    }//GEN-LAST:event_lblJCMSTutorialsMouseClicked

    private void lblJCMSProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSProductsMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSProductsURL());
    }//GEN-LAST:event_lblJCMSProductsMouseClicked

    private void lblJCMSSupportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSSupportMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSSupportURL());
    }//GEN-LAST:event_lblJCMSSupportMouseClicked

    private void lblJCMSWebInstallationGuideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSWebInstallationGuideMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSInstallationGuideURL());
    }//GEN-LAST:event_lblJCMSWebInstallationGuideMouseClicked

    private void lblJCMSUsersGuideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSUsersGuideMouseClicked
        BrowserLaunch.openURL(this.getPropertiesDTO().getJCMSWebUsersGuideURL());
    }//GEN-LAST:event_lblJCMSUsersGuideMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFAQs;
    private javax.swing.JLabel lblJCMSHome;
    private javax.swing.JLabel lblJCMSProducts;
    private javax.swing.JLabel lblJCMSSupport;
    private javax.swing.JLabel lblJCMSTutorials;
    private javax.swing.JLabel lblJCMSUsersGuide;
    private javax.swing.JLabel lblJCMSWebFoum;
    private javax.swing.JLabel lblJCMSWebInstallationGuide;
    private javax.swing.JLabel lblKnownIssues;
    // End of variables declaration//GEN-END:variables
}
