/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/

package org.jax.cs.jcmsWebInstaller;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author cnh
 */
public class JCMSWebInstallerAboutBox extends javax.swing.JDialog {
    PropertiesDTO propertiesDTO = null;
    
    /**
     * Creates new form JCMSWebInstallerAboutBox
     */
    public JCMSWebInstallerAboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ImageIcon icon = createImageIcon("resources/jcmsWeb_header.jpg", "a pretty but meaningless splat");
        this.lblJCMSHeader = new JLabel("Image and Text", icon, JLabel.CENTER);        
        
        propertiesDTO = new PropertiesDTO();
        this.lblJCMSWebInstallerVersion.setText(propertiesDTO.getJCMSWebInstallerVersion());
        this.lblJCMSWebInstallerVendor.setText(propertiesDTO.getJCMSWebInstallerVendor());
        this.lblJCMSWebInstallerDescription.setText(propertiesDTO.getJCMSWebInstallerDescription());
    }

    /** Returns an ImageIcon, or null if the path was invalid. */
    protected ImageIcon createImageIcon(String path, String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJCMSHome = new javax.swing.JLabel();
        lblJCMSHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblJCMSWebInstallerVersion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJCMSWebInstallerVendor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblJCMSWebInstallerDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblJCMSHome.setForeground(new java.awt.Color(0, 0, 255));
        lblJCMSHome.setText("JAX Colony Management System");
        lblJCMSHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblJCMSHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJCMSHomeMouseClicked(evt);
            }
        });

        lblJCMSHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJCMSHeader.setText("JCMS Web Installer");

        jLabel1.setText("JCMS Web Installer Version:  ");

        lblJCMSWebInstallerVersion.setText("jLabel2");

        jLabel2.setText("JCMS Web Installer Vendor:  ");

        lblJCMSWebInstallerVendor.setText("jLabel2");

        jLabel3.setText("JCMS Web Installer Description:  ");

        lblJCMSWebInstallerDescription.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJCMSHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJCMSHome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJCMSWebInstallerVersion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJCMSWebInstallerVendor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJCMSWebInstallerDescription)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJCMSHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblJCMSWebInstallerVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblJCMSWebInstallerVendor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblJCMSWebInstallerDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJCMSHome)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblJCMSHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJCMSHomeMouseClicked
        String jcmsWebNewInstallURL = "http://colonymanagement.jax.org/products-2/jcms-web/";
        BrowserLaunch.openURL(propertiesDTO.getJCMSHomeURL());
    }//GEN-LAST:event_lblJCMSHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCMSWebInstallerAboutBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCMSWebInstallerAboutBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCMSWebInstallerAboutBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCMSWebInstallerAboutBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JCMSWebInstallerAboutBox dialog = new JCMSWebInstallerAboutBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblJCMSHeader;
    private javax.swing.JLabel lblJCMSHome;
    private javax.swing.JLabel lblJCMSWebInstallerDescription;
    private javax.swing.JLabel lblJCMSWebInstallerVendor;
    private javax.swing.JLabel lblJCMSWebInstallerVersion;
    // End of variables declaration//GEN-END:variables
}
